name: CI
run-name: "`${{ github.actor }}` triggered workflow from a `${{ github.event_name }}` on `${{ github.ref_name }}` : ${{ github.event.head_commit.message || github.event.workflow_run.head_commit.message }}"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - lib/**
      - src/**

env:
  TARGET1: glados-compiler
  TARGET2: glados-vm

jobs:
  check-coding-style:
    name: Checking coding style
    runs-on: ubuntu-24.04
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
    - name: Cloning repository
      uses: actions/checkout@v4
      timeout-minutes: 2

    - name: Running bannana-checker
      uses: lszsrd/ci-composite-actions/coding-style-checker@v1
      timeout-minutes: 2

  check-compilation:
    name: Checking compilation
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, self-hosted, windows-2022]

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Building `${{ env.TARGET1 }}` and `${{ env.TARGET2 }}` binaries
        run: |
          cabal update
          make
        timeout-minutes: 10

      - name: Checking -x permission
        if: matrix.os != 'windows-2022'
        run: |
          if [ ! -x ./${{ env.TARGET1 }} ]; then
            echo "::error::Binary ${{ env.TARGET1 }} does not has -x permission"
            exit 1
          fi
          if [ ! -x ./${{ env.TARGET2 }} ]; then
            echo "::error::Binary ${{ env.TARGET2 }} does not has -x permission"
            exit 1
          fi
        timeout-minutes: 2

  run-tests:
    name: Running tests
    runs-on: ubuntu-24.04
<<<<<<< HEAD
=======
    #container: epitechcontent/epitest-docker:latest
>>>>>>> e65e5aa1daf8eb8db5e1284194cec20bc09c513b
    needs: check-compilation

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Running unit tests
=======
      - name: Running unit tests on `${{ env.TARGET }}`
>>>>>>> e65e5aa1daf8eb8db5e1284194cec20bc09c513b
        run: |
          cabal update
          make tests_run
        timeout-minutes: 2

<<<<<<< HEAD
      - name: Running functional tests
        run: |
          exit 0
=======
      - name: Running functional tests on `${{ env.TARGET }}`
        run: |
          ./tests/functionaltests.sh
>>>>>>> e65e5aa1daf8eb8db5e1284194cec20bc09c513b
        timeout-minutes: 2
