name: CI
run-name: "`${{ github.actor }}` triggered workflow from a `${{ github.event_name }}` on `${{ github.ref_name }}` : ${{ github.event.head_commit.message || github.event.workflow_run.head_commit.message }}"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - lib/**
      - src/**

env:
  TARGET1: glados-compiler
  TARGET2: glados-vm

jobs:
  check-coding-style:
    name: Checking coding style
    runs-on: ubuntu-24.04
    container: ghcr.io/epitech/coding-style-checker:latest

    steps:
    - name: Cloning repository
      uses: actions/checkout@v4
      timeout-minutes: 2

    - name: Running bannana-checker
      uses: lszsrd/ci-composite-actions/coding-style-checker@v1
      timeout-minutes: 2

  check-compilation:
    name: Checking compilation
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, self-hosted, windows-2022]

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Building `${{ env.TARGET1 }}` and `${{ env.TARGET2 }}` binaries
        run: |
          cabal update
          make
        timeout-minutes: 10

      - name: Checking -x permission
        if: matrix.os != 'windows-2022'
        run: |
          if [ ! -x ./${{ env.TARGET1 }} ]; then
            echo "::error::Binary ${{ env.TARGET1 }} does not has -x permission"
            exit 1
          fi
          if [ ! -x ./${{ env.TARGET2 }} ]; then
            echo "::error::Binary ${{ env.TARGET2 }} does not has -x permission"
            exit 1
          fi
        timeout-minutes: 2

  run-tests:
    name: Running tests
    runs-on: ubuntu-24.04
    needs: check-compilation

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Running unit tests
        run: |
          cabal update
          make tests_run
        timeout-minutes: 2

      - name: Running functional tests
        run: |
          exit 0
        timeout-minutes: 2
