name: Release
run-name: "`${{ github.actor }}` created tag `${{ github.ref_name }}`"

on:
  push:
    tags:
      - 'v*'

env:
  TARGET: glados

jobs:
  build-target-windows:
    name: Building target ${{ env.TARGET }} for Windows
    runs-on: windows-2022

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Building {{ env.TARGET }}
        run: |
          cabal update
          make
          mv ${{ env.TARGET }}.exe ${{ env.TARGET }}-windows.exe
          zip --junk-paths ${{ env.TARGET }} ${{ env.TARGET }}-windows.exe LICENSE.md docs/README.md

      - name: Uploading Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: ${{ env.TARGET }}.zip

  build-target-linux:
    name: Building target ${{ env.TARGET }} for Ubuntu 24.04
    runs-on: ubuntu-24.04
    needs: build-target-windows

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Downloading Windows binary
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.TARGET }}

      - name: Building {{ env.TARGET }}
        run: |
          cabal update
          make
          mv ${{ env.TARGET }} ${{ env.TARGET }}-linux
          zip --junk-paths ${{ env.TARGET }} ${{ env.TARGET }}-linux

      - name: Uploading Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: ${{ env.TARGET }}.zip

  build-release:
    name: Building release for tag ${{ github.ref }}
    runs-on: ubuntu-24.04
    needs: build-target-linux

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        timeout-minutes: 2

      - name: Downloading Windows and Linux binaries
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.TARGET }}

      - name: Creating Release
        id: creating_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Uploading release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.creating_release.outputs.upload_url }}
          asset_path: ./${{ env.TARGET }}.zip
          asset_name: ${{ env.TARGET }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
